build:
    image: mltsp/drone
    commands:
        - git log -1
        - ./.drone/build.sh

clone:
  depth: 1
  path: github.com/mltsp/mltsp

notify:
    gitter:
        webhook: https://webhooks.gitter.im/e/90fff13a43dbc71cc72d

matrix:
    PYTHON_VERSION:
        - 2.7
        - 3.4

