image: mltsp/drone
git:
  path: github.com/mltsp/mltsp
env:
script:
  - ./.drone/build.sh
  - ./.drone/stop_docker.sh
services:
  - library/rethinkdb
notify:
  email:
    recipients:
      - stefanv@berkeley.edu
  webhook:
    on_started: false
    on_success: true
    on_failure: true
